spring:
  datasource:
    url: jdbc:postgresql://localhost:5411/travelplanner
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    user:
      name: admin
      password: admin
server:
  port: 8089
